### ISSUE TITLE
When trying to run it I got the following error on the CMD. How to fix it?

### ISSUE THREAD

**Issue by GBAS-BCN** [nezza/ISO7816Analyzer#3]
C:\Users\xxxx\ISO7816Analyzer>python3 build_analyzer.py
Running on Windows
g++ -I"./AnalyzerSDK/include" -O3 -w -c -fpic -o"release/ISO7816Analyzer.o" "source/ISO7816Analyzer.cpp"
'g++' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\xxxx\ISO7816Analyzer\build_analyzer.py", line 76, in <module>
    run_command(release_command)
  File "C:\Users\xxxx\ISO7816Analyzer\build_analyzer.py", line 53, in run_command
    raise Exception("Shell execution returned nonzero status")
Exception: Shell execution returned nonzero status

C:\Users\xxxx\ISO7816Analyzer>

**Comment by nezza** [comment]
Looks like you don't have G++ installed.

Unfortuantely I have no experience with building Saleae analyzers on Windows, I suggest checking whether the SampleAnalyzer builds: https://github.com/saleae/SampleAnalyzer

If it doesn't I believe the bug is with your configuration

**Comment by GBAS-BCN** [comment]
What's G++?

**Comment by nezza** [comment]
A compiler
